export const SET_ROUND = 'SET/SET_ROUND';
export const SET_ACTIVE_BIRD_INFO_ID = 'SET/SET_ACTIVE_BIRD_INFO_ID';
export const SET_TRUE_ANSWER = 'SET/SET_TRUE_ANSWER';
export const SET_POINTS = 'SET/SET_POINTS';
